### ISSUE TITLE
Unsupported Major Minor version when trying to compile Bal file from intelij 

### ISSUE THREAD

**Issue by nirosh4** [ballerina-lang/plugin-intellij#813]
Im getting unsupported major minor version error as bellow when attempting to build Ballerina code from intelj idea. 
Note that I can execute ballerina files using CLI without any issue. 
Any Idea on how to resolve it ?

Intelij IDE version : 2017.2
Ballerina intelij plugin version : 0.9.9
Ballerina version : 0.95.8
Java version : 1.8.0_60

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/ballerinalang/launcher/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)

![1111](https://user-images.githubusercontent.com/36333704/36063046-f0ec0f8c-0e9d-11e8-945a-e14e7724fea9.png)

**Comment by Shan1024** [comment]
@nirosh4 - Can you check with the latest plugin and see whether this issue still exists?

**Comment by Shan1024** [comment]
Cannot reproduce.
